### ISSUE TITLE
如何配置MySQL的端口

### ISSUE THREAD

**Issue by yfh19961130** [wenhaofan/AutuBlog#1]
### **如何配置MySQL的端口**
怎么修改MySQL端口啊. 我用的不是3306.  恳请答复下. 

**建议不要在开源项目中过多使用硬编码**
作者有自己的习惯, 用起来挺顺手的. 而他人配置起来就可能会出问题.

**Comment by wenhaofan** [comment]
修改/AutuBlog/src/main/resources/dev_blog_config.txt中的jdbcUrl即可
